name: HelloGFC

on: [push]

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Primer escenario
        run: echo "Hola, mundo, desde GFC"
      - name: Segundo escenario
        run:
          echo "Step2. Segundo saludo"
          echo "Step3. tercer saludo"
          
